### ISSUE TITLE
Error Changing Fonts

### ISSUE THREAD

**Issue by gartnera** [royriojas/eslint-friendly-formatter#30]
On the following line, you try to use the `\033]50` `\007` combination to set the font of your output. 

https://github.com/royriojas/eslint-friendly-formatter/blob/32a1e55d29fbbd3bb15a723c16f06b729de8d27d/index.js#L248

However, setting the font to `CurrentDir=...` doesn't make any sense. What are you trying to do here? Can we remove this or set it to something sensible?

On most terminals this is silently ignored, but mintty raises an error every time (https://github.com/mintty/wsltty/issues/87).

**Comment by royriojas** [comment]
Hi @gartnera That is just a trick for interm to understand relative paths. But we can hide behind a flag so it doesn't impact mintty users.

Pull requests are welcome if you are interested.

**Comment by krubokrubo** [comment]
I had the same problem using eslint from an ssh session from cygwin.  I had used `vue init webpack` which gave me eslint-friendly-formatter@^3.0.0, which still has the bug. Thanks to your fix, I was able to solve it by upgrading to eslint-friendly-formatter@4.

However, it would be really nice if you could publish this fix as version 3.0.1, since tools like vue-cli are still installing eslint-friendly-formatter@^3.0.0.  These tools would automatically update to version 3.0.1, but they don't automatically update to 4. Would you consider publishing this fix as 3.0.1?

**Comment by royriojas** [comment]
hi @krubokrubo 

Of course. Will check how difficult would it be to have the fix on this repo. Thanks for reporting it.
